# -*- coding: utf-8 -*-
"""Intern_assignment_Digipplus

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/106L7wGyXnl2DvXCK0mjlHyt1BZRS1X-2
"""

import requests


def fetchandsavetofile(url,path) :
    r = requests.get(url)
    with open(path, "w") as f:
        f.write(r.text)


url = "https://www.careerpower.in/books-and-authors.html"

fetchandsavetofile(url,"/content/data/book_authors.html")

import bs4
import csv
from bs4 import BeautifulSoup
with open("/content/data/book_authors.html","r") as f :
  html_doc = f.read()

soup = BeautifulSoup(html_doc,'html.parser')

#print(soup.prettify())
#print(soup.title.string)
names = [h.text for h in soup.find_all('td')]

#print(names)
with open('book_data.csv','w',newline = '') as csvfile :
  writer = csv.writer(csvfile)
  writer.writerow(["Book Name", "Author Name"])  # Write header row

  for i in range(3, len(names), 2):
    writer.writerow([names[i], names[i + 1]])

print(f"CSV file has been created.")
